
#
# The default config will add wands to chests in world and world_nether
#

# Set this to 0 to disable MCStats metrics collection
metrics_level: 5

# Enable or disable event handlers
entity_spawn_listener: true
entity_death_listener: true
entity_target_listener: false

# Define per-world chunk and entity rules here
worlds:
  world:
     chunk_generate:
        items:
          class: MagicChestPopulator
          base_probability:
            0: 100
            1: 80
          item_probability:
            sp|100: 1
            sp|80: 2
            sp|70: 3
            sp|60: 4
            sp|50: 5
            sp|40: 10
            sp|30: 20
            sp|25: 30
            sp|20: 40
            sp|15: 50
  world_nether:
     entity_spawn:
        pigzombie_master_sword:
          target_type: pig_zombie
          probability: 1
          min_y: 0
          allow_indoors: true
          cooldown: 0
          class: EquipmentRule
          item: iron_sword
     chunk_generate:
        items:
          class: MagicChestPopulator
          base_probability:
            0: 100
            1: 80
            2: 2
          item_probability:
            sp|200: 1
            sp|150: 2
            sp|100: 3
            sp|75: 4
            sp|50: 5
            sp|45: 10
            sp|40: 20
            sp|30: 30
            sp|25: 40
            sp|20: 50