
#
# The default config will add wands to chests in world and world_nether
#

# Set this to 0 to disable MCStats metrics collection
metrics_level: 5

# Define per-world chunk and entity rules here
worlds:
  world:
     chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 60
          base_probability:
            0: 100
            1: 80
          wand_probability:
            guest: 80
            villager: 60
            knight: 20
            wizard: 1
            random(1): 200
            random(2): 150
            random(5): 80
            random(10): 10
            random(20): 5
            random(30): 1
  world_nether:
     chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 100
          base_probability:
            0: 100
            1: 80
            2: 2
          wand_probability:
            fire_1: 200
            fire_2: 100
            fire: 10
            random(1): 100
            random(2): 75
            random(5): 50
            random(10): 15
            random(20): 10
            random(30): 5