
#
# The default config will add wands to chests in world and world_nether
#

# Set this to 0 to disable MCStats metrics collection
metrics_level: 5

# Enable or disable event handlers
entity_spawn_listener: true
entity_target_listener: true

# Define per-world chunk and entity rules here
worlds:
  world:
     chunk_generate:
        items:
          class: MagicChestPopulator
          base_probability:
            0: 100
            1: 80
          item_probability:
            camera: 10
            stun: 60
            fling: 20
            blink: 1
            petrify: 200
            boon: 150
            curse: 80
            poison: 10
            torture: 5
            arrow: 5
            kill: 1
  world_nether:
     chunk_generate:
        items:
          class: MagicChestPopulator
          base_probability:
            0: 100
            1: 80
            2: 2
          item_probability:
            fireball: 200
            fire: 100
            fire|2: 10
            flamethrower: 100
            lava: 75
            lightning: 50
            boon: 15
            grenade: 10