
#
# The default config will add wands to chests in world and world_nether
#

# Set this to 0 to disable MCStats metrics collection
metrics_level: 5

# Enable or disable event handlers
entity_spawn_listener: true
entity_target_listener: true

# Define per-world chunk and entity rules here
worlds:
  world:
     chunk_generate:
        wands: 
          class: WandChestPopulator
          base_probability:
            0: 100
            1: 80
          wand_probability:
            guest: 80
            villager: 60
            battle: 20
            wizard: 1
            student(1): 200
            apprentice(2): 150
            apprentice(5): 80
            master(10): 10
            master(20): 5
            master(30): 1
  world_nether:
     chunk_generate:
        wands: 
          class: WandChestPopulator
          base_probability:
            0: 100
            1: 80
            2: 2
          wand_probability:
            fire_student: 200
            fire_apprentice: 100
            fire: 10
            student(1): 100
            apprentice(2): 75
            apprentice(5): 50
            master(10): 15
            master(20): 10
            master(30): 5