
#
# The default config will add wands to chests in world and world_nether
#

# Set this to 0 to disable MCStats metrics collection
metrics_level: 5

terrain:
   origin_latitude: 47.353720
   origin_longitude: -123.088604
   #origin_latitude: 52
   #origin_longitude: 0