#
# This is an example configuration to make an otherworldly "Other Side" world
# populated by Endermen.
#

worlds:
  world:
    entity_spawn:
        enderman_1_villager:
          class: ReplaceRule
          target_type: enderman
          replace_type: villager
    chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 60
          base_probability:
            0: 100
            1: 80
          wand_probability:
            guest: 80
            villager: 60
            knight: 20
            wizard: 1
            random(1): 200
            random(2): 150
            random(5): 80
            random(10): 10
            random(20): 5
            random(30): 1
  world_nether:
     chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 100
          base_probability:
            0: 100
            1: 80
            2: 2
          wand_probability:
            fire_1: 200
            fire_2: 100
            fire: 10
            random(1): 100
            random(2): 75
            random(5): 50
            random(10): 15
            random(20): 10
            random(30): 5
  world_other:
     entity_spawn:
          chicken_1_hunter:
            target_type: chicken
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material mossy_cobblestone seed_radius 2
          chicken_2_virus:
            target_type: chicken
            probability: 0.02
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - virus material obsidian seed_radius 3
            
          pig_1_hunter:
            target_type: pig
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material diamond_ore seed_radius 2
          pig_2_enderman:
            target_type: pig
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
          sheep_1_hunter:
            target_type: sheep
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material packed_ice seed_radius 2
          sheep_2_enderman:
            target_type: sheep
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
          creeper_1_enderman:
            target_type: creeper
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
          zombie_1_hunter:
            target_type: zombie
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material huge_mushroom_1 seed_radius 2
          zombie_2_hunter:
            target_type: zombie
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material huge_mushroom_2 seed_radius 2
          zombie_3_hunter:
            target_type: zombie
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material leaves seed_radius 2
          zombie_4_hunter:
            target_type: zombie
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material leaves_2 seed_radius 2
          zombie_5_virus:
            target_type: zombie
            probability: 0.02
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - virus material huge_mushroom_1 seed_radius 3
          zombie_6_enderman:
            target_type: zombie
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
          skeleton_1_enderman:
            target_type: skeleton
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
          spider_1_hunter:
            target_type: spider
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material melon_block seed_radius 2
          spider_2_hunter:
            target_type: spider
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material pumpkin seed_radius 2
          spider_3_hunter:
            target_type: spider
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material soul_sand seed_radius 2
          spider_4_hunter:
            target_type: spider
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material clay seed_radius 2
          spider_5_virus:
            target_type: spider
            probability: 0.02
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - virus material melon_block seed_radius 3
          spider_6_enderman:
            target_type: spider
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman

          pig_2_enderman:
            target_type: pig
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
          horse_1_skeleton_horse:
            target_type: horse
            probability: 0.8
            min_y: 63
            class: ReplaceRule
            replace_type: horse
            replace_sub_type: skeleton_horse
          horse_2_undead_horse:
            target_type: horse
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: horse
            replace_sub_type: undead_horse
          
          cow_1_giant:
            target_type: cow
            probability: 0.01
            min_y: 63
            class: ReplaceRule
            replace_type: giant
          cow_2_enderman:
            target_type: cow
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
          slime_1_lavaslime:
            target_type: slime
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: lavaslime
            
          bat_1_blaze:
            target_type: bat
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: blaze
                        
          enderman_1_hunter:
            target_type: enderman
            probability: 0.05
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material lapis_block seed_radius 2
          enderman_2_hunter:
            target_type: enderman
            probability: 0.04
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material gold_block seed_radius 2
          enderman_3_hunter:
            target_type: enderman
            probability: 0.01
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material diamond_block seed_radius 2
          enderman_4_hunter:
            target_type: enderman
            probability: 0.02
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material iron_block seed_radius 2
          enderman_5_hunter:
            target_type: enderman
            probability: 0.04
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material obsidian seed_radius 2
          enderman_6_hunter:
            target_type: enderman
            probability: 0.01
            min_y: 63
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - virus material obsidian seed_radius 3  
     chunk_generate:
        replace:
          class: ReplacePopulator
          replace:
            grass: mycel
            dirt: netherrack
            stone: ender_stone
            leaves: glowstone
            leaves_2: stained_glass|5
            log: quartz_block|2
            log_2: glowstone
            water: stained_glass|9
            stationary_water: stained_glass|3
            lava: stained_glass|13
            stationary_lava: stained_glass|1
            sandstone: stained_clay:10
            gravel: soul_sand
            sand: sand:1
            cactus: nether_fence
            long_grass: brown_mushroom
            yellow_flower: red_mushroom
            red_rose: torch
            wood: brick
            double_plant: cobble_fence
            fence: iron_fence
            iron_fence: cobble_fence
            cobblestone: nether_brick
            glass: stained_glass|10
            thin_glass: stained_glass_pane|9
            ice: stained_glass|11
            packed_ice: stained_glass|11
            clay: stained_clay|10
            snow_block: quartz_block
            coal_ore: quartz_ore
            diamond_ore: quartz_ore
            emerald_ore: quartz_ore
            iron_ore: quartz_ore
            gold_ore: quartz_ore
            wool: gold_block|2
            pumpkin: jack_o_lantern
            melon_block: torch
        wands: 
          class: WandChestPopulator
          base_probability:
            0: 20
            1: 70
            2: 20
            3: 5
          wand_probability:
            nether: 50
            ender: 60
            elder: 1
            recalltoken: 100
            mana1: 100
            mana2: 50
            mana3: 10
            random(10): 200
            random(20): 150
            random(50): 80