#
# This is an example configuration to make an otherworldly "Other Side" world
# populated by Endermen.
#

worlds:
  world:
     chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 60
          base_probability:
            0: 100
            1: 80
          wand_probability:
            guest: 80
            villager: 60
            knight: 20
            wizard: 1
            random(1): 200
            random(2): 150
            random(5): 80
            random(10): 10
            random(20): 5
            random(30): 1
  world_nether:
     chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 100
          base_probability:
            0: 100
            1: 80
            2: 2
          wand_probability:
            fire_1: 200
            fire_2: 100
            fire: 10
            random(1): 100
            random(2): 75
            random(5): 50
            random(10): 15
            random(20): 10
            random(30): 5
  world_other:
     entity_spawn:
        replace:
          class: ReplaceSpawnHandler
          replace: 
            pig: enderman
            sheep: enderman
            creeper: enderman
            zombie: enderman
            skeleton: enderman
            spider: enderman
            horse1: horse,horse|skeleton_horse@0.8,1
            horse2: horse,horse|undead_horse@1.0,2
            cow1: cow,giant@0.01,3
            cow2: cow,enderman@1,4
            slime: lavaslime
            bat: blaze
            chicken1: chicken,spell|hunter material lapis_block seed_radius 2@0.01,20
            chicken2: chicken,spell|hunter material gold_block seed_radius 2@0.01,21
            chicken3: chicken,spell|hunter material diamond_block seed_radius 2@0.01,22
            chicken4: chicken,spell|hunter material iron_block seed_radius 2@0.01,23
            chicken5: chicken,spell|hunter material obsidian seed_radius 2@0.05,24
     chunk_generate:
        replace:
          class: ReplacePopulator
          replace:
            grass: mycel
            dirt: netherrack
            stone: ender_stone
            leaves: glowstone
            leaves_2: stained_glass|5
            log: quartz_block|2
            log_2: glowstone
            water: stained_glass|9
            stationary_water: stained_glass|3
            lava: stained_glass|13
            stationary_lava: stained_glass|1
            sandstone: monster_eggs:5
            gravel: soul_sand
            sand: sand:1
            cactus: nether_fence
            long_grass: brown_mushroom
            yellow_flower: red_mushroom
            red_rose: torch
            wood: brick
            double_plant: nether_fence
            fence: nether_fence
            cobblestone: nether_brick
            glass: stained_glass|10
            thin_glass: stained_glass_pane|9
            ice: stained_glass|11
            packed_ice: stained_glass|11
            clay: stained_clay|10
            snow_block: quartz_block
            coal_ore: quartz_ore
            diamond_ore: quartz_ore
            emerald_ore: quartz_ore
            iron_ore: quartz_ore
            gold_ore: quartz_ore
            wool: gold_block|2
            pumpkin: jack_o_lantern
            melon_block: torch
        wands: 
          class: WandChestPopulator
          base_probability:
            0: 20
            1: 70
            2: 20
            3: 5
          wand_probability:
            nether: 50
            ender: 60
            elder: 1
            recalltoken: 100
            mana1: 100
            mana2: 50
            mana3: 10
            random(10): 200
            random(20): 150
            random(50): 80