#
# This is an example configuration to make an otherworldly "Other Side" world
# populated by Endermen.
#

worlds:
  world:
    entity_spawn:
        replace:
          class: ReplaceSpawnHandler
          replace: 
            enderman: villager
    chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 60
          base_probability:
            0: 100
            1: 80
          wand_probability:
            guest: 80
            villager: 60
            knight: 20
            wizard: 1
            random(1): 200
            random(2): 150
            random(5): 80
            random(10): 10
            random(20): 5
            random(30): 1
  world_nether:
     chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 100
          base_probability:
            0: 100
            1: 80
            2: 2
          wand_probability:
            fire_1: 200
            fire_2: 100
            fire: 10
            random(1): 100
            random(2): 75
            random(5): 50
            random(10): 15
            random(20): 10
            random(30): 5
  world_other:
     entity_spawn:
        replace:
          class: ReplaceSpawnHandler
          replace: 
            hunterchicken: chicken>63,spell|hunter material mossy_cobblestone seed_radius 2@0.05,30
            viruschicken: chicken>63,spell|virus material obsidian seed_radius 1@0.02,24
            hunterpig: pig>63,spell|hunter material diamond_ore seed_radius 2@0.05,31
            pig: enderman@1,100
            huntersheep: sheep>63,spell|hunter material packed_ice seed_radius 2@0.05,32
            sheep: enderman@1,101
            creeper: enderman@1,102
            zombie: enderman@1,103
            hunterzombie1: zombie>63,spell|hunter material huge_mushroom_1 seed_radius 2@0.03,1000
            hunterzombie2: zombie>63,spell|hunter material huge_mushroom_2 seed_radius 2@0.03,1001
            hunterzombie3: zombie>63,spell|hunter material leaves seed_radius 2@0.03,1002
            hunterzombie4: zombie>63,spell|hunter material leaves_2 seed_radius 2@0.03,1003
            viruszombie1: zombie>63,spell|virus material huge_mushroom_1 seed_radius 3@0.01,1004
            skeleton: enderman@1,104
            spider: enderman@1,105
            hunterspider1: spider>63,spell|hunter material melon_block seed_radius 2@0.05,1010
            hunterspider2: spider>63,spell|hunter material pumpkin seed_radius 2@0.05,1011
            hunterspider3: spider>63,spell|hunter material soul_sand seed_radius 2@0.05,1012
            hunterspider4: spider>63,spell|hunter material clay seed_radius 2@0.05,1013
            virusspider1: spider>63,spell|virus material melon_block seed_radius 3@0.01,1014
            horse1: horse,horse|skeleton_horse@0.8,1
            horse2: horse,horse|undead_horse@1.0,2
            cow1: cow,giant@0.01,3
            cow2: cow,enderman@1.0,4
            slime: lavaslime
            bat: blaze
            hunter1: enderman>63,spell|hunter material lapis_block seed_radius 2@0.02,20
            hunter2: enderman>63,spell|hunter material gold_block seed_radius 2@0.02,21
            hunter3: enderman>63,spell|hunter material diamond_block seed_radius 2@0.02,22
            hunter4: enderman>63,spell|hunter material iron_block seed_radius 2@0.02,23
            hunter5: enderman>63,spell|hunter material obsidian seed_radius 2@0.03,24
            virus1: enderman>63,spell|virus material obsidian seed_radius 1@0.01,24
     chunk_generate:
        replace:
          class: ReplacePopulator
          replace:
            grass: mycel
            dirt: netherrack
            stone: ender_stone
            leaves: glowstone
            leaves_2: stained_glass|5
            log: quartz_block|2
            log_2: glowstone
            water: stained_glass|9
            stationary_water: stained_glass|3
            lava: stained_glass|13
            stationary_lava: stained_glass|1
            sandstone: stained_clay:10
            gravel: soul_sand
            sand: sand:1
            cactus: nether_fence
            long_grass: brown_mushroom
            yellow_flower: red_mushroom
            red_rose: torch
            wood: brick
            double_plant: cobble_fence
            fence: iron_fence
            iron_fence: cobble_fence
            cobblestone: nether_brick
            glass: stained_glass|10
            thin_glass: stained_glass_pane|9
            ice: stained_glass|11
            packed_ice: stained_glass|11
            clay: stained_clay|10
            snow_block: quartz_block
            coal_ore: quartz_ore
            diamond_ore: quartz_ore
            emerald_ore: quartz_ore
            iron_ore: quartz_ore
            gold_ore: quartz_ore
            wool: gold_block|2
            pumpkin: jack_o_lantern
            melon_block: torch
        wands: 
          class: WandChestPopulator
          base_probability:
            0: 20
            1: 70
            2: 20
            3: 5
          wand_probability:
            nether: 50
            ender: 60
            elder: 1
            recalltoken: 100
            mana1: 100
            mana2: 50
            mana3: 10
            random(10): 200
            random(20): 150
            random(50): 80