#
# This is an example configuration to make an otherworldly "Other Side" world
# populated by Endermen.
#

worlds:
  world:
    entity_spawn:
        enderman_1_villager:
          class: ReplaceRule
          target_type: enderman
          replace_type: witch
    chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 60
          base_probability:
            0: 100
            1: 80
          wand_probability:
            guest: 80
            villager: 60
            knight: 20
            wizard: 1
            random(1): 200
            random(2): 150
            random(5): 80
            random(10): 10
            random(20): 5
            random(30): 1
  world_nether:
    chunk_generate:
        wands: 
          class: WandChestPopulator
          max_y: 100
          base_probability:
            0: 100
            1: 80
            2: 2
          wand_probability:
            fire_1: 200
            fire_2: 100
            fire: 10
            random(1): 100
            random(2): 75
            random(5): 50
            random(10): 15
            random(20): 10
            random(30): 5
  world_other:
      entity_spawn:
     
          skeleton_1_defender:
            target_type: skeleton
            probability: 0.001
            min_y: 63
            y_offset: 6
            allow_indoors: false
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - defender material mossy_cobblestone seed_radius 2
            
          creeper_1_hunter:
            target_type: creeper
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material redstone_ore seed_radius 2
          creeper_2_hunter:
            target_type: creeper
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material packed_ice seed_radius 2
          creeper_3_virus:
            target_type: creeper
            probability: 0.001
            y_offset: 24
            min_y: 63
            allow_indoors: false
            class: CastRule
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - virus material obsidian seed_radius 3
            
          zombie_1_hunter:
            target_type: zombie
            probability: 0.01
            y_offset: 6
            min_y: 63
            class: CastRule
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material huge_mushroom_1 seed_radius 2
          zombie_2_hunter:
            target_type: zombie
            probability: 0.01
            y_offset: 6
            min_y: 63
            class: CastRule
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material huge_mushroom_2 seed_radius 2
          zombie_3_hunter:
            target_type: zombie
            probability: 0.01
            y_offset: 6
            min_y: 63
            class: CastRule
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material monster_egg seed_radius 2
          zombie_4_hunter:
            target_type: zombie
            probability: 0.01
            y_offset: 6
            min_y: 63
            class: CastRule
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material wool seed_radius 2
          zombie_5_virus:
            target_type: zombie
            probability: 0.005
            y_offset: 24
            min_y: 63
            class: CastRule
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - virus material huge_mushroom_1 seed_radius 3
          zombie_6_defender:
            target_type: zombie
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 12
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - defender material hay_block seed_radius 3
                        
          spider_1_hunter:
            target_type: spider
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material melon_block seed_radius 2
          spider_2_hunter:
            target_type: spider
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material pumpkin seed_radius 2
          spider_3_hunter:
            target_type: spider
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material soul_sand seed_radius 2
          spider_4_hunter:
            target_type: spider
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material clay seed_radius 2
          spider_5_virus:
            target_type: spider
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 24
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - virus material melon_block seed_radius 3
          spider_6_worm:
            target_type: spider
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 32
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - worm material clay seed_radius 3
              
          enderman_1_hunter:
            target_type: enderman
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material lapis_block seed_radius 2
          enderman_2_hunter:
            target_type: enderman
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material log seed_radius 2
          enderman_3_hunter:
            target_type: enderman
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material log_2 seed_radius 2
          enderman_4_hunter:
            target_type: enderman
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material wool seed_radius 2
          enderman_5_hunter:
            target_type: enderman
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 6
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - hunter material obsidian seed_radius 2
          enderman_6_worm:
            target_type: enderman
            probability: 0.001
            min_y: 63
            class: CastRule
            y_offset: 24
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - worm material log seed_radius 3
          enderman_7_worm:
            target_type: enderman
            probability: 0.01
            min_y: 63
            class: CastRule
            y_offset: 32
            allow_indoors: false
            spells: 
              - flare pdy 1 pdx 0 pdz 0 ty ~10
              - worm material obsidian seed_radius 3
          enderman_8_giant:
            target_type: enderman
            probability: 0.1
            min_y: 63
            class: ReplaceRule
            replace_type: giant
     
     # None of these are likely to spawn here since there is no grass!
              
          horse_1_skeleton_horse:
            target_type: horse
            probability: 0.5
            min_y: 63
            class: ReplaceRule
            replace_type: horse
            replace_sub_type: skeleton_horse
          horse_2_undead_horse:
            target_type: horse
            probability: 1
            min_y: 63
            class: ReplaceRule
            replace_type: horse
            replace_sub_type: undead_horse
     
          chicken_999_enderman:
            target_type: chicken
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          pig_999_enderman:
            target_type: pig
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          sheep_999_enderman:
            target_type: sheep
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          pig_999_enderman:
            target_type: pig
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          horse_999_enderman:
            target_type: horse
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          cow_998_mushroomcow:
            target_type: cow
            probability: 0.8
            min_y: 63
            class: ReplaceRule
            replace_type: mushroomcow
          cow_999_enderman:
            target_type: cow
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
       # Default fallbacks
       
          creeper_999_enderman:
            target_type: creeper
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          zombie_999_enderman:
            target_type: zombie
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          skeleton_999_enderman:
            target_type: skeleton
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          spider_999_enderman:
            target_type: spider
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman

       # Other Mob Replacement
         
          villager_1_pigman:
            class: ReplaceRule
            probability: 1.0
            target_type: villager
            replace_type: pigzombie
            
          slime_1_lavaslime:
            target_type: slime
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: lavaslime
            
          bat_1_blaze:
            target_type: bat
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: blaze
            
      chunk_generate:
        replace:
          class: ReplacePopulator
          replace:
            grass: mycel
            dirt: netherrack
            stone: ender_stone
            leaves: glowstone
            leaves_2: stained_glass|*
            log: stained_glass_pane|*
            log_2: glowstone
            hard_clay: stained_glass|12
            water: stained_glass|9
            stationary_water: stained_glass|3
            lava: stained_glass|13
            stationary_lava: stained_glass|1
            sandstone: stained_clay:10
            stained_clay: stained_glass:*
            gravel: soul_sand
            sand: sand:1
            cactus: nether_fence
            long_grass: brown_mushroom
            yellow_flower: red_mushroom
            red_rose: torch
            wood: brick
            double_plant: cobble_wall
            fence: iron_fence
            iron_fence: cobble_wall
            cobblestone: nether_brick
            mossy_cobblestone: iron_block
            mob_spawner: diamond_block
            glass: stained_glass|10
            thin_glass: stained_glass_pane|9
            ice: stained_glass|11
            packed_ice: stained_glass|11
            clay: stained_clay|10
            snow_block: quartz_block
            coal_ore: quartz_ore
            diamond_ore: quartz_ore
            emerald_ore: quartz_ore
            iron_ore: quartz_ore
            gold_ore: quartz_ore
            wool: log|2
            pumpkin: jack_o_lantern
            melon_block: torch
            huge_mushroom_1: stained_glass:*
            huge_mushroom_2: stained_glass_pane:*
        wands: 
          class: WandChestPopulator
          base_probability:
            0: 20
            1: 70
            2: 20
            3: 5
          wand_probability:
            nether: 50
            ender: 60
            elder: 1
            recalltoken: 100
            mana1: 100
            mana2: 50
            mana3: 10
            random(10): 200
            random(20): 150
            random(50): 80
            
  world_other_backup:
      entity_spawn:
     
     # None of these are likely to spawn here since there is no grass!
              
          horse_1_skeleton_horse:
            target_type: horse
            probability: 0.5
            min_y: 63
            class: ReplaceRule
            replace_type: horse
            replace_sub_type: skeleton_horse
          horse_2_undead_horse:
            target_type: horse
            probability: 1
            min_y: 63
            class: ReplaceRule
            replace_type: horse
            replace_sub_type: undead_horse
     
          chicken_999_enderman:
            target_type: chicken
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          pig_999_enderman:
            target_type: pig
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          sheep_999_enderman:
            target_type: sheep
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          pig_999_enderman:
            target_type: pig
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          horse_999_enderman:
            target_type: horse
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          cow_998_mushroomcow:
            target_type: cow
            probability: 0.8
            min_y: 63
            class: ReplaceRule
            replace_type: mushroomcow
          cow_999_enderman:
            target_type: cow
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
            
       # Default fallbacks
       
          creeper_999_enderman:
            target_type: creeper
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          zombie_999_enderman:
            target_type: zombie
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          skeleton_999_enderman:
            target_type: skeleton
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman
          spider_999_enderman:
            target_type: spider
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: enderman

       # Other Mob Replacement
         
          villager_1_pigman:
            class: ReplaceRule
            probability: 1.0
            target_type: villager
            replace_type: pigzombie
            
          slime_1_lavaslime:
            target_type: slime
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: lavaslime
            
          bat_1_blaze:
            target_type: bat
            probability: 1.0
            min_y: 63
            class: ReplaceRule
            replace_type: blaze
            
      chunk_generate:
        replace:
          class: ReplacePopulator
          replace:
            grass: mycel
            dirt: netherrack
            stone: ender_stone
            leaves: glowstone
            leaves_2: stained_glass|*
            log: stained_glass_pane|*
            log_2: glowstone
            hard_clay: stained_glass|12
            water: stained_glass|9
            stationary_water: stained_glass|3
            lava: stained_glass|13
            stationary_lava: stained_glass|1
            sandstone: stained_clay:10
            stained_clay: stained_glass:*
            gravel: soul_sand
            sand: sand:1
            cactus: nether_fence
            long_grass: brown_mushroom
            yellow_flower: red_mushroom
            red_rose: torch
            wood: brick
            double_plant: cobble_wall
            fence: iron_fence
            iron_fence: cobble_wall
            cobblestone: nether_brick
            mossy_cobblestone: iron_block
            mob_spawner: diamond_block
            glass: stained_glass|10
            thin_glass: stained_glass_pane|9
            ice: stained_glass|11
            packed_ice: stained_glass|11
            clay: stained_clay|10
            snow_block: quartz_block
            coal_ore: quartz_ore
            diamond_ore: quartz_ore
            emerald_ore: quartz_ore
            iron_ore: quartz_ore
            gold_ore: quartz_ore
            wool: log|2
            pumpkin: jack_o_lantern
            melon_block: torch
            huge_mushroom_1: stained_glass:*
            huge_mushroom_2: stained_glass_pane:*